### ISSUE TITLE
python init fail

### ISSUE THREAD

**Issue by razaqq** [MurkyOwl/CopyPasta#1]
Fatal Python error: initfsencoding: unable to load the file system codec
zipimport.ZipImportError: can't find module 'encodings'

Current thread 0x00001920 (most recent call first):

when launching on windows 10
only happens with newer version old one works fine

**Comment by MurkyOwl** [comment]
Hi @razaqq thanks for reporting this! At first glance it looks to be an issue with PyInstaller, so I'll see if i can replicate and also look at re-bundling the application.

**Comment by MurkyOwl** [comment]
Ok, so this was an issue with PyInstaller and Python 3.7 I downgraded to 3.6 and it should be working now

https://github.com/MurkyOwl/CopyPasta/releases/tag/V1.12

**Comment by razaqq** [comment]
thanks for the super fast rely!
