### ISSUE TITLE
[Request] Show M/B instead of full value

### ISSUE THREAD

**Issue by razaqq** [MurkyOwl/CopyPasta#2]
Title says it,
1B is way quicker to read than 1.000.000.000 ISK

**Comment by MurkyOwl** [comment]
I'll look into how to implement this although I will say that being able to look at a number and see if its millions or billions can be a very important skill in eve!

**Comment by razaqq** [comment]
I know but when you are highsec ganking, you dont really have the time ;)

**Comment by MurkyOwl** [comment]
Added in https://github.com/MurkyOwl/CopyPasta/releases/tag/V1.2

Sorry for the long wait!
